{% set name = "beav" %}
{% set version = "0.0.2" %}
{% set sha256 = "7278f73aaaa3af20f18e7b17cd43c4ec20c966a6495ef11bd19ebaa470c5e8b2"

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/weisberglab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - python
  run: 
    - bakta
    - integron_finder
    - macsyfinder
    - fastani
    - antismash
    - hmmer
    - emboss
    - blast-legacy
    - bbmap
test:
  commands:
    - beav

about:
  home: https://github.com/weisberglab/beav
  license: GPL
  summary: "beav: Bacterial Element Annotation reVamped"

extra:
  identifiers:
    - doi:none
